# Generated by Django 4.2.5 on 2024-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
